# Generated by Django 2.1 on 2018-11-12 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bogotrash_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cedula',
            field=models.IntegerField(),
        ),
    ]
