# Generated by Django 2.1 on 2018-11-17 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bogotrash_app', '0002_auto_20181112_1600'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tipodesecho',
            name='centro',
        ),
        migrations.AddField(
            model_name='centro',
            name='tipo_desecho',
            field=models.ManyToManyField(to='bogotrash_app.TipoDesecho'),
        ),
        migrations.AlterField(
            model_name='queja',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='img/fotosapp/'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='catalogo',
            field=models.ManyToManyField(blank=True, null=True, to='bogotrash_app.Catalogo'),
        ),
    ]
