# Generated by Django 2.0.9 on 2018-11-17 16:24

from django.db import migrations
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('bogotrash_app', '0003_auto_20181117_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='queja',
            name='dirección',
            field=django_google_maps.fields.AddressField(blank=True, max_length=200, null=True, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='queja',
            name='geolocacion',
            field=django_google_maps.fields.GeoLocationField(blank=True, max_length=100, null=True, verbose_name='Coordenadas'),
        ),
    ]
