# Generated by Django 2.0.9 on 2018-11-17 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bogotrash_app', '0005_auto_20181117_1133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queja',
            name='ubicacion',
        ),
    ]
