# Generated by Django 2.0.9 on 2018-11-17 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bogotrash_app', '0006_remove_queja_ubicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='cedula',
            field=models.IntegerField(unique=True),
        ),
    ]
